version: "3.8"
services:
  bbdd:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_DB=${DB_NAME}"
  deno-app:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - "bbdd"